### ISSUE TITLE
dopenssl for newer versions of OpenSSL

### ISSUE THREAD

**Issue by kingsley-cheung** [infinitdotio/dopenssl#4]
Are there plans to keep doenssl working with newer versions of OpenSSL like 1.1.1? Thanks.

**Comment by mefyl** [comment]
dopenssl was essentially a component of Infinit, which was discontinued by Docker. This part of the code is not being used or maintained currently, so I would say no in the foreseeable future. Contributions welcome though.

**Comment by kingsley-cheung** [comment]
Understood. I'll take a look into it if time permits.
